-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 17:44:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_vetcon
-- -----------------------------------------------------
-- This database is for Nepal Veterinary Consultancy.

-- -----------------------------------------------------
-- Schema db_vetcon
--
-- This database is for Nepal Veterinary Consultancy.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_vetcon` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_vetcon` ;

-- -----------------------------------------------------
-- Table `db_vetcon`.`vBatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vBatch` (
  `vbatch_id` MEDIUMINT(50) NOT NULL AUTO_INCREMENT,
  `vbatch_start_date` DATE NOT NULL,
  `vbatch_end_date` DATE NULL,
  `vbatch_type` VARCHAR(10) NOT NULL,
  `vbatch_flock_size` INT NOT NULL,
  `vbatch_flocks` INT(5) NOT NULL,
  `vbatch_heads` INT(10) NULL,
  `vFarm_vfarm_id` MEDIUMINT(50) NOT NULL,
  PRIMARY KEY (`vbatch_id`, `vFarm_vfarm_id`),
  INDEX `fk_vBatch_vFarm1_idx` (`vFarm_vfarm_id` ASC) VISIBLE,
  CONSTRAINT `fk_vBatch_vFarm1`
    FOREIGN KEY (`vFarm_vfarm_id`)
    REFERENCES `db_vetcon`.`vFarm` (`vfarm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vCase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vCase` (
  `vcase_id` MEDIUMINT(50) NOT NULL AUTO_INCREMENT,
  `vcase_date` DATE NOT NULL,
  `vcase_time` TIME NOT NULL,
  `vcase_description` LONGTEXT NOT NULL,
  `vcase_symptoms` LONGTEXT NOT NULL,
  `vcase_diagnosis` MEDIUMTEXT NOT NULL,
  `vcase_prescription` LONGTEXT NOT NULL,
  `vClient_vclient_phone` INT(10) NOT NULL,
  PRIMARY KEY (`vcase_id`, `vClient_vclient_phone`),
  INDEX `fk_vCase_vClient1_idx` (`vClient_vclient_phone` ASC) VISIBLE,
  CONSTRAINT `fk_vCase_vClient1`
    FOREIGN KEY (`vClient_vclient_phone`)
    REFERENCES `db_vetcon`.`vClient` (`vclient_phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vCase_has_vDisease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vCase_has_vDisease` (
  `vCase_vcase_id` MEDIUMINT(50) NOT NULL,
  `vDisease_vdisease_id` INT(10) NOT NULL,
  PRIMARY KEY (`vCase_vcase_id`, `vDisease_vdisease_id`),
  INDEX `fk_vCase_has_vDisease_vDisease1_idx` (`vDisease_vdisease_id` ASC) VISIBLE,
  INDEX `fk_vCase_has_vDisease_vCase1_idx` (`vCase_vcase_id` ASC) VISIBLE,
  CONSTRAINT `fk_vCase_has_vDisease_vCase1`
    FOREIGN KEY (`vCase_vcase_id`)
    REFERENCES `db_vetcon`.`vCase` (`vcase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vCase_has_vDisease_vDisease1`
    FOREIGN KEY (`vDisease_vdisease_id`)
    REFERENCES `db_vetcon`.`vDisease` (`vdisease_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vClient` (
  `vclient_phone` INT(10) NOT NULL,
  `vclient_fname` VARCHAR(40) NOT NULL,
  `vclient_lname` VARCHAR(45) NOT NULL,
  `vclient_email` VARCHAR(45) NULL,
  `vclient_description` LONGTEXT NOT NULL,
  `vclient_address` VARCHAR(100) NOT NULL,
  `vclient_tole` VARCHAR(45) NOT NULL,
  `vFarm_vfarm_id` MEDIUMINT(50) NOT NULL,
  PRIMARY KEY (`vclient_phone`, `vFarm_vfarm_id`),
  INDEX `fk_vClient_vFarm1_idx` (`vFarm_vfarm_id` ASC) VISIBLE,
  CONSTRAINT `fk_vClient_vFarm1`
    FOREIGN KEY (`vFarm_vfarm_id`)
    REFERENCES `db_vetcon`.`vFarm` (`vfarm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vClient_has_vPet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vClient_has_vPet` (
  `vClient_vclient_phone` INT(10) NOT NULL,
  `vPet_vpet_id` MEDIUMINT(50) NOT NULL,
  PRIMARY KEY (`vClient_vclient_phone`, `vPet_vpet_id`),
  INDEX `fk_vClient_has_vPet_vPet1_idx` (`vPet_vpet_id` ASC) VISIBLE,
  INDEX `fk_vClient_has_vPet_vClient1_idx` (`vClient_vclient_phone` ASC) VISIBLE,
  CONSTRAINT `fk_vClient_has_vPet_vClient1`
    FOREIGN KEY (`vClient_vclient_phone`)
    REFERENCES `db_vetcon`.`vClient` (`vclient_phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vClient_has_vPet_vPet1`
    FOREIGN KEY (`vPet_vpet_id`)
    REFERENCES `db_vetcon`.`vPet` (`vpet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vDisease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vDisease` (
  `vdisease_id` INT(10) NOT NULL AUTO_INCREMENT,
  `vdisease_name` VARCHAR(100) NOT NULL,
  `vdisease_symptoms` LONGTEXT NOT NULL,
  `vdisease_description` LONGTEXT NOT NULL,
  PRIMARY KEY (`vdisease_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vFarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vFarm` (
  `vfarm_id` MEDIUMINT(50) NOT NULL AUTO_INCREMENT,
  `vfarm_name` VARCHAR(100) NOT NULL,
  `vfarm_address` VARCHAR(100) NOT NULL,
  `vfarm_tole` VARCHAR(100) NOT NULL,
  `vfarm_estd` DATE NOT NULL,
  PRIMARY KEY (`vfarm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vPet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vPet` (
  `vpet_id` MEDIUMINT(50) NOT NULL AUTO_INCREMENT,
  `vpet_start_date` DATE NOT NULL,
  `vpet_end_date` DATE NULL,
  `vpet_type` VARCHAR(20) NOT NULL,
  `vpet_name` VARCHAR(20) NOT NULL,
  `vpet_color` VARCHAR(10) NOT NULL,
  `vpet_weight` INT(4) NOT NULL,
  `vpet_height` INT NOT NULL,
  `vpet_description` LONGTEXT NULL,
  PRIMARY KEY (`vpet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vUser` (
  `vuser_phone` INT(10) NOT NULL,
  `vuser_fname` VARCHAR(40) NOT NULL,
  `vuser_lname` VARCHAR(45) NOT NULL,
  `vuser_email` VARCHAR(45) NOT NULL,
  `vuser_description` LONGTEXT NOT NULL,
  `vuser_address` VARCHAR(100) NOT NULL,
  `vsuer_tole` VARCHAR(45) NOT NULL,
  `vuser_post` VARCHAR(45) NOT NULL,
  `vuser_access` TINYINT(1) NOT NULL DEFAULT 0,
  `vpassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vuser_phone`),
  UNIQUE INDEX `vuser_email_UNIQUE` (`vuser_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vetcon`.`vUser_has_vCase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vetcon`.`vUser_has_vCase` (
  `vUser_vuser_phone` INT(10) NOT NULL,
  `vCase_vcase_id` MEDIUMINT(50) NOT NULL,
  PRIMARY KEY (`vUser_vuser_phone`, `vCase_vcase_id`),
  INDEX `fk_vUser_has_vCase_vCase1_idx` (`vCase_vcase_id` ASC) VISIBLE,
  INDEX `fk_vUser_has_vCase_vUser_idx` (`vUser_vuser_phone` ASC) VISIBLE,
  CONSTRAINT `fk_vUser_has_vCase_vUser`
    FOREIGN KEY (`vUser_vuser_phone`)
    REFERENCES `db_vetcon`.`vUser` (`vuser_phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vUser_has_vCase_vCase1`
    FOREIGN KEY (`vCase_vcase_id`)
    REFERENCES `db_vetcon`.`vCase` (`vcase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
